name = "Eco Predict"
uid = "8ffe5730-2ad3-4f5b-81b8-56622508c7e9"
version = 1
copyright = "GPL v3"
description = "Testing out a few things. Hopefully plot future (predicted) eco."
author = "iliis"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
conflicts = {}
before = {}
after = {}
