name = "Eco Viz"
uid = "8ffe5730-2ad3-4f5b-81b8-54-EcoViz-V1"
version = 1
copyright = "GPL v3"
description = "Plot reclaim as variably sized points, making it easier to see big chunks at a glance."
author = "iliis"
url = "https://github.com/iliis/EcoViz"
icon = "/mods/EcoViz/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
conflicts = {}
before = {}
after = {}
