name = "Eco Predict"
uid = "8ffe5730-2ad3-4f5b-81b8-EcoPredictV1"
version = 1
copyright = "GPL v3"
description = "Testing out a few things. Hopefully plot future (predicted) eco."
author = "iliis"
url = "https://github.com/iliis/ecopredict"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
conflicts = {}
before = {}
after = {}
